#! /bin/bash

# 2022-07-20 This is for the stock cardano-node running on the public testnet
# in the Babbage and later eras
# cd $HOME/dev/marlowe
# configDir=cardano-node/configuration
# source "local-cardano-service-configs/configuration.env"
# ./build-node/bin/cardano-node run \
#   --config "$configDir/cardano/testnet-config.json" \
#   --topology "$configDir/cardano/testnet-topology.json" \
#   --database-path node.db \
#   --socket-path ${CARDANO_NODE_SOCKET_PATH:-node.socket} \
#   --port "$CARDANO_NODE_PORT" \
#   $@

# 2022-07-19 This was for the marlowe-specific testnets
cd $HOME/dev/marlowe
configDir=local-cardano-service-configs
source "$configDir/configuration.env"
./build-node/bin/cardano-node run \
  --config node.config \
  --topology node.topology \
  --database-path node.db \
  --socket-path ${CARDANO_NODE_SOCKET_PATH:-node.socket} \
  --port "$CARDANO_NODE_PORT" \
  $@

# 2022-04-08 This was from mucking around with alonzo back in the fall of 2021
# Take note of the RTS switches at the end! Would we ever need these?

#!/nix/store/kxj6cblcsd1qcbbxlmbswwrn89zcmgd6-bash-4.4-p23/bin/bash
#
# configDir="/home/dino/.config/alonzo-testnet"
# 
# # WARNING: If the cardano-node version changes THIS SCRIPT WILL NOT NOTICE AND MUST BE HAND-EDITED!!!
# # This means the /nix/store/blahblah... path below
# 
# exec /nix/store/xbq4yynx9my6ysggvmam2a27cr5i4pgc-cardano-node-exe-cardano-node-1.30.1/bin/cardano-node run \
#   --config "$configDir/testnet-config.json" \
#   --database-path public-testnet/db-public-testnet \
#   --topology "$configDir/testnet-topology.json" \
#   --host-addr 0.0.0.0 --port 3001 \
#   --socket-path public-testnet/node.socket \
#   +RTS -N2 -A16m -qg -qb --disable-delayed-os-memory-return -RTS $@
