#! /bin/bash

cd $HOME/dev/marlowe
configDir=local-cardano-service-configs
source "$configDir/configuration.env"
./build-chain-index/plutus-chain-index start-index \
  --network-id "$CARDANO_TESTNET_MAGIC" \
  --db-path chain-index.db/ci.sqlite \
  --socket-path ${CARDANO_NODE_SOCKET_PATH:-node.socket} \
  --port "$CARDANO_CHAIN_INDEX_PORT"
