#! /bin/bash

cd $HOME/dev/marlowe
configDir=local-cardano-service-configs
source "$configDir/configuration.env"
./build-wallet/bin/cardano-wallet serve \
  --testnet iohk-nix/cardano-lib/marlowe-dev/byron-genesis.json \
  --database wallet.db \
  --node-socket node.socket \
  --port "$CARDANO_WALLET_PORT"
